name: scavontime
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  animate_do: ^3.0.2
  dio: ^5.0.2
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.1.1
  flutter_riverpod: ^2.2.0
  form_builder_validators: ^9.1.0
  go_router: ^6.2.0
  google_fonts: ^4.0.3
  http: ^1.1.2
  provider: ^6.1.1
 

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/loaders/
    - assets/images/
    - google_fonts/montserrat_alternates/
